[SYSINFRA-992] reflow/taskdb: Fix flakiness in dynamodb_test
Summary:
Flakiness was induced because sometimes the order of queries (issued to `mockDynamodbQueryTasks`)
would be different.
While the test includes sorting to account for this, the tests were accessing a different
singleton field `qinput` instead of always usng `qinputs`.

As a result, we weren't actually testing the last query previously.

Test Plan:
The issue was clearly evident when running the test repeatedly.
```
>  go test -test.count=50 -test.run=TestTasksTimeBucketQuery
​--- FAIL: TestTasksTimeBucketQuery (0.00s)
    dynamodb_test.go:1175: keepalive: expected 2021-11-11T22:21:18Z, got 2021-11-12T22:21:18Z
    dynamodb_test.go:1175: key condition: expected #Date = :date and Keepalive > :ka, got #Date = :date and Keepalive < :ka
    dynamodb_test.go:1175: keepalive: expected 2021-11-11T22:21:18Z, got 2021-11-12T22:21:18Z
    dynamodb_test.go:1175: key condition: expected #Date = :date and Keepalive > :ka, got #Date = :date and Keepalive < :ka
​--- FAIL: TestTasksTimeBucketQuery (0.00s)
    dynamodb_test.go:1175: keepalive: expected 2021-11-11T22:21:18Z, got 2021-11-12T22:21:18Z
    dynamodb_test.go:1175: key condition: expected #Date = :date and Keepalive > :ka, got #Date = :date and Keepalive < :ka
    dynamodb_test.go:1175: keepalive: expected 2021-11-11T22:21:18Z, got 2021-11-12T22:21:18Z
    dynamodb_test.go:1175: key condition: expected #Date = :date and Keepalive > :ka, got #Date = :date and Keepalive < :ka
​--- FAIL: TestTasksTimeBucketQuery (0.00s)
    dynamodb_test.go:1175: keepalive: expected 2021-11-11T22:21:18Z, got 2021-11-12T22:21:18Z
    dynamodb_test.go:1175: key condition: expected #Date = :date and Keepalive > :ka, got #Date = :date and Keepalive < :ka
    dynamodb_test.go:1175: keepalive: expected 2021-11-11T22:21:18Z, got 2021-11-12T22:21:18Z
    dynamodb_test.go:1175: key condition: expected #Date = :date and Keepalive > :ka, got #Date = :date and Keepalive < :ka
FAIL
exit status 1
FAIL	github.com/grailbio/reflow/taskdb/dynamodbtask	0.236s
```
With the fix, they are not flaky anymore:
```
> go test -test.count=10000 -test.run=TestTasksTimeBucketQuery
PASS
ok  	github.com/grailbio/reflow/taskdb/dynamodbtask	0.742s

> go test -test.count=10000 -test.run=TestRunsTimeBucketQuery
PASS
ok  	github.com/grailbio/reflow/taskdb/dynamodbtask	0.757s
```

Reviewers: ghorrell

Reviewed By: ghorrell

Subscribers: dnicolaou, pboyapalli

Differential Revision: https://phabricator.grailbio.com/D67416

fbshipit-source-id: 55cb9e9