[SYSINFRA-1037] reflow/runner: Retry Eval errors if underlying causes are Restartable.
Summary:
- `Restartable` treats `Eval` errors differently, as defined by the updated godoc.
- Add an integration test which simulates the exact situation (which caused run failure) in SYSINFRA-976.
  However, the integration test verifies that the run is retried and it succeeds upon retry.
- Minor fix in `program_eval_test`: Explicitly declare copies of loop variables, since they are accessed
  concurrently.
- Cosmetic changes to how retry attempts are logged.
- Since this change classifies `Temporary` errors as `Restartable`, we end up with `9` total attempts
  for execs which return a `Temporary` exit code (ie, `exit code 75`)

Note: This revision addresses SYSINFRA-976

Test Plan:
Unit and integration tests.
Specifically, the newly added integration test `//go/src/grail.com/reflow/integration/transient_failure_retry_test.go`
simulates the exact situation and confirms that with this change, the evaluation will be retried successfully.
That is, without D67758, this new integration test fails:
```
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	2021/11/22 22:47:32 scheduler task 75a9d663 (flow e843eb3b): unloading val<>
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	2021/11/22 22:47:32 scheduler task 75a9d663 (flow e843eb3b): unloaded val<>
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	2021/11/22 22:47:32 scheduler task 75a9d663 (flow e843eb3b): unloading val<.=48d2adf0 44B>
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	panic: unload: negative ref count: sha256:48d2adf0f99469f1a4096bb83023ace15bbf866af6f6ec1d82bd1a3f044ccfb6
transient_failure_retry_test:SchedTopDownLocal:reflow_run:
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	goroutine 462 [running]:
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	github.com/grailbio/reflow/local.(*Executor).unload(0xc000ea4900, {0xc000b8ef58, 0x1}, {{0x0, 0xc0012b4330, 0x3}, 0xc0006f1bf0})
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 		go/src/github.com/grailbio/reflow/local/executor.go:398 +0x6ca
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	github.com/grailbio/reflow/local.(*Executor).Unload(0x1e1e97d, {0x21a5c50, 0xc000dfac80}, {{0x0, 0x10, 0x1987820}, 0xc0006f1bf0})
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 		go/src/github.com/grailbio/reflow/local/executor.go:439 +0x2d
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	github.com/grailbio/reflow/sched.unload.func1.1()
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 		go/src/github.com/grailbio/reflow/sched/scheduler.go:645 +0x138
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	golang.org/x/sync/errgroup.(*Group).Go.func1()
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 		external/org_golang_x_sync/errgroup/errgroup.go:57 +0x67
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	created by golang.org/x/sync/errgroup.(*Group).Go
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 		external/org_golang_x_sync/errgroup/errgroup.go:54 +0x92
2021/11/22 22:47:32 cleaning up: s3://reflow-unittest/integration/HDCAgIIfjnqqsPbjcbjrQyOBPXYrFWLT/transient_failure_retry_test/SchedTopDownLocal/ (1 files)
    --- FAIL: TestTransientFailureRetry/transient_failure_retry_test_SchedTopDownLocal (43.20s)
        transient_failure_retry_test.go:93: exit status 2
```
With D67758, this new integration test will pass:
```
...
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	2021/11/22 22:24:58 marking run for retry after restartable error evaluation error:
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 		s3blob.Download grail-reflow-cache objects/sha256:9e18fea5d265255d68eadbc09868ad8b7821f18447e24f7f3b4dbc4283b41596: gave up after 3 tries: too many tries
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	2021/11/22 22:24:58 runner state 'Retry': retry 1/3 (last attempt at: 2021-11-22T22:24:19Z) due to: evaluation error:
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 		s3blob.Download grail-reflow-cache objects/sha256:9e18fea5d265255d68eadbc09868ad8b7821f18447e24f7f3b4dbc4283b41596: gave up after 3 tries: too many tries
...
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	2021/11/22 22:25:26 total n=4 time=7s
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 		ident                                n   ncache runtime(m) cpu         mem(GiB)    disk(GiB)   tmp(GiB)    requested
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 		transient_failure_retry_eval.CatCopy 2   0      0/0/0      0.0/0.0/0.0 0.0/0.0/0.0 0.0/0.0/0.0 0.0/0.0/0.0 {mem:500.0MiB cpu:1 disk:0B}
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 		transient_failure_retry_eval.Sleep   1   0      0/0/0      0.0/0.0/0.0 0.0/0.0/0.0 0.0/0.0/0.0 0.0/0.0/0.0 {mem:500.0MiB cpu:1 disk:0B}
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 		transient_failure_retry_eval.out1    1   0
transient_failure_retry_test:SchedTopDownLocal:reflow_run:
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	2021/11/22 22:25:26 result: 9e18fea5
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	2021/11/22 22:25:26 waiting for 1 background tasks to complete
transient_failure_retry_test:SchedTopDownLocal:reflow_run: 	2021/11/22 22:25:26 Saved all logs in task db
2021/11/22 22:25:26 cleaning up: s3://reflow-unittest/integration/pNZKbBOYTXCThuUQBSIotYslyoSfgPRb/transient_failure_retry_test/SchedTopDownLocal/ (1 files)
PASS
```

Reviewers: ghorrell, awissmann

Reviewed By: ghorrell

Subscribers: dnicolaou, pboyapalli

Differential Revision: https://phabricator.grailbio.com/D67768

fbshipit-source-id: 7085d90