reflow/trace: Increase timeouts to reduce flakiness
Summary:
Increase the timeouts since the tests seem to be flaky with the current values:
```
        localtracer_test.go:336: took 20.29432ms, expected less than 20ms
        localtracer_test.go:336: took 218.224099ms, expected less than 200ms
        localtracer_test.go:336: took 20.858289ms, expected less than 20ms
        localtracer_test.go:336: took 210.2486ms, expected less than 200ms
        localtracer_test.go:336: took 2.044784496s, expected less than 2s
```

Test Plan:
Unit tests.

Previously, my first attempt resulted in the following:
```
> go test -test.count 10 -run Contention
​--- FAIL: TestLocalTracerContention (1.33s)
    --- FAIL: TestLocalTracerContention/1,000_concurrent_traces (0.02s)
        localtracer_test.go:336: took 24.845185ms, expected less than 20ms
FAIL
exit status 1

> go test -test.count 100 -run Contention
PASS
ok  	github.com/grailbio/reflow/trace/localtrace	113.139s
```

With the change, this doesn't happen (at least hasn't happened yet).

Reviewers: pboyapalli

Reviewed By: pboyapalli

Subscribers: dnicolaou

Differential Revision: https://phabricator.grailbio.com/D58059

fbshipit-source-id: e3d5b1d